const i18nKeys = {
  // localization keys go here
  actorTypes: {
    character: 'TB2.ActorTypeCharacter',
  },
  itemTypes: {
    belief: 'TB2.ItemTypeBelief',
    instinct: 'TB2.ItemTypeInstinct',
    creed: 'TB2.ItemTypeCreed',
    goal: 'TB2.ItemTypeGoal',
    gear: 'TB2.ItemTypeGear',
    trait: 'TB2.ItemTypeTrait',
    skill: 'TB2.ItemTypeSkill',
    wise: 'TB2.ItemTypeWise',
    relationship: 'TB2.ItemTypeRelationship',
    spell: 'TB2.ItemTypeSpell',
    invocation: 'TB2.ItemTypeInvocation',
    level: 'TB2.ItemTypeLevelBenefit',
    property: 'TB2.ItemTypeProperty',
    class: 'TB2.ItemTypeClass',
  },
  skills: {
    alchemist: 'TB2.TestAlchemist',
    arcanist: 'TB2.TestArcanist',
    armorer: 'TB2.TestArmorer',
    beggar: 'TB2.TestBeggar',
    butcher: 'TB2.TestButcher',
    carpenter: 'TB2.TestCarpenter',
    cartographer: 'TB2.TestCartographer',
    commander: 'TB2.TestCommander',
    cook: 'TB2.TestCook',
    criminal: 'TB2.TestCriminal',
    dungeoneer: 'TB2.TestDungeoneer',
    enchanter: 'TB2.TestEnchanter',
    fighter: 'TB2.TestFighter',
    fisher: 'TB2.TestFisher',
    gambler: 'TB2.TestGambler',
    haggler: 'TB2.TestHaggler',
    healer: 'TB2.TestHealer',
    hunter: 'TB2.TestHunter',
    jeweler: 'TB2.TestJeweler',
    laborer: 'TB2.TestLaborer',
    loremaster: 'TB2.TestLoremaster',
    manipulator: 'TB2.TestManipulator',
    mentor: 'TB2.TestMentor',
    orator: 'TB2.TestOrator',
    pathfinder: 'TB2.TestPathfinder',
    peasant: 'TB2.TestPeasant',
    persuader: 'TB2.TestPersuader',
    rider: 'TB2.TestRider',
    ritualist: 'TB2.TestRitualist',
    sailor: 'TB2.TestSailor',
    sapper: 'TB2.TestSapper',
    scavenger: 'TB2.TestScavenger',
    scholar: 'TB2.TestScholar',
    scout: 'TB2.TestScout',
    smith: 'TB2.TestSmith',
    steward: 'TB2.TestSteward',
    stonemason: 'TB2.TestStonemason',
    strategist: 'TB2.TestStrategist',
    survivalist: 'TB2.TestSurvivalist',
    tanner: 'TB2.TestTanner',
    theologian: 'TB2.TestTheologian',
    weaver: 'TB2.TestWeaver',
  },
  stock: {
    changeling: 'TB2.StockChangeling',
    halfling: 'TB2.StockHalfling',
    human: 'TB2.StockHuman',
    elf: 'TB2.StockElf',
    dwarf: 'TB2.StockDwarf',
  },
  attributes: {
    health: 'TB.AttrHealth',
    will: 'TB.AttrWill',
    resources: 'TB.AttrResources',
    circles: 'TB.AttrCircles',
    nature: 'TB.AttrNature',
  },
  traits: {
    alert: 'TB2.TraitAlert',
    betweenTwoWorlds: 'TB2.TraitBetweenTwoWorlds',
    bodyguard: 'TB2.TraitBodyguard',
    cautious: 'TB2.TraitCautious',
    clever: 'TB2.TraitClever',
    compassionate: 'TB2.TraitCompassionate',
    conservative: 'TB2.TraitConservative',
    cynical: 'TB2.TraitCynical',
    defiant: 'TB2.TraitDefiant',
    desperate: 'TB2.TraitDesperate',
    determined: 'TB2.TraitDetermined',
    devilMayCare: 'TB2.TraitDevilMayCare',
    driven: 'TB2.TraitDriven',
    emaciated: 'TB2.TraitEmaciated',
    fearful: 'TB2.TraitFearful',
    graceful: 'TB2.TraitGraceful',
    huldrekall: 'TB2.TraitHuldrekall',
    hungry: 'TB2.TraitHungry',
    independent: 'TB2.TraitIndependent',
    innocent: 'TB2.TraitInnocent',
    jovial: 'TB2.TraitJovial',
    juvenile: 'TB2.TraitJuvenile',
    keenEar: 'TB2.TraitKeenEar',
    leader: 'TB2.TraitLeader',
    loyal: 'TB2.TraitLoyal',
    naturalBearings: 'TB2.TraitNaturalBearings',
    nightOwl: 'TB2.TraitNightOwl',
    nimble: 'TB2.TraitNimble',
    opportunistic: 'TB2.TraitOpportunistic',
    pragmatic: 'TB2.TraitPragmatic',
    restless: 'TB2.TraitRestless',
    rotund: 'TB2.TraitRotund',
    rover: 'TB2.TraitRover',
    short: 'TB2.TraitShort',
    skittish: 'TB2.TraitSkittish',
    stout: 'TB2.TraitStout',
    stubborn: 'TB2.TraitStubborn',
    suspicious: 'TB2.TraitSuspicious',
    tough: 'TB2.TraitTough',
    voiceOfThunder: 'TB2.TraitVoiceOfThunder',
    weatherSense: 'TB2.TraitWeatherSense',
    wise: 'TB2.TraitWise',
    adventurous: 'TB2.TraitAdventurous',
    bitter: 'TB2.TraitBitter',
    bold: 'TB2.TraitBold',
    bornOfEarthAndStone: 'TB2.TraitBornOfEarthAndStone',
    brave: 'TB2.TraitBrave',
    calm: 'TB2.TraitCalm',
    cunning: 'TB2.TraitCunning',
    curious: 'TB2.TraitCurious',
    defender: 'TB2.TraitDefender',
    earlyRiser: 'TB2.TraitEarlyRiser',
    extravagant: 'TB2.TraitExtravagant',
    extrovert: 'TB2.TraitExtrovert',
    fearless: 'TB2.TraitFearless',
    fiery: 'TB2.TraitFiery',
    firstborn: 'TB2.TraitFirstborn',
    foolhardy: 'TB2.TraitFoolhardy',
    generous: 'TB2.TraitGenerous',
    heartOfBattle: 'TB2.TraitHeartOfBattle',
    hiddenDepths: 'TB2.TraitHiddenDepths',
    honorable: 'TB2.TraitHonorable',
    jaded: 'TB2.TraitJaded',
    loner: 'TB2.TraitLoner',
    lost: 'TB2.TraitLost',
    quickWitted: 'TB2.TraitQuickWitted',
    quiet: 'TB2.TraitQuiet',
    roughHands: 'TB2.TraitRoughHands',
    scarred: 'TB2.TraitScarred',
    sharpEyed: 'TB2.TraitSharpEyed',
    skeptical: 'TB2.TraitSkeptical',
    skinny: 'TB2.TraitSkinny',
    steadyHands: 'TB2.TraitSteadyHands',
    stoic: 'TB2.TraitStoic',
    tall: 'TB2.TraitTall',
    thoughtful: 'TB2.TraitThoughtful',
    touchedByTheGods: 'TB2.TraitTouchedByTheGods',
    wizardsSight: 'TB2.TraitWizardsSight',
  },
  classes: {
    burglar: 'TB2.ClassBurglar',
    magician: 'TB2.ClassMagician',
    outcast: 'TB2.ClassOutcast',
    ranger: 'TB2.ClassRanger',
    theurge: 'TB2.ClassTheurge',
    warrior: 'TB2.ClassWarrior',
    shaman: 'TB2.ClassShaman',
    thief: 'TB2.ClassThief',
    skald: 'TB2.ClassSkald',
    bounder: 'TB2.ClassBounder',
    dreamwalker: 'TB2.ClassDreamwalker',
    guide: 'TB2.ClassGuide',
    scion: 'TB2.ClassScion',
    sorcerer: 'TB2.ClassSorcerer',
    stoneteller: 'TB2.ClassStoneteller',
  },
};
export const TB = {
  ASCII: String.raw`
---------------------------------------------------------------------------------------
 _____ ___________  _____  _   _ ______ _____  ___  ______ ___________    _____  _____
|_   _|  _  | ___ \/  __ \| | | || ___ \  ___|/ _ \ | ___ \  ___| ___ \  / __  \|  ___|
  | | | | | | |_/ /| /  \/| |_| || |_/ / |__ / /_\ \| |_/ / |__ | |_/ /  \' / /'| |__
  | | | | | |    / | |    |  _  || ___ \  __||  _  ||    /|  __||    /     / /  |  __|
  | | \ \_/ / |\ \ | \__/\| | | || |_/ / |___| | | || |\ \| |___| |\ \   ./ /___| |___
  \_/  \___/\_| \_| \____/\_| |_/\____/\____/\_| |_/\_| \_\____/\_| \_|  \_____/\____/
=======================================================================================`,
  i18n: i18nKeys,
  i18nKeys,
  icons: {},
};
