const i18nKeys = {
  //  TODO localization keys go here

  tests: {
    alchemist: 'TB2.TestAlchemist',
    arcanist: 'TB2.TestArcanist',
    armorer: 'TB2.TestArmorer',
    beggar: 'TB2.TestBeggar',
    butcher: 'TB2.TestButcher',
    carpenter: 'TB2.TestCarpenter',
    cartographer: 'TB2.TestCartographer',
    commander: 'TB2.TestCommander',
    cook: 'TB2.TestCook',
    criminal: 'TB2.TestCriminal',
    dungeoneer: 'TB2.TestDungeoneer',
    enchanter: 'TB2.TestEnchanter',
    fighter: 'TB2.TestFighter',
    fisher: 'TB2.TestFisher',
    gambler: 'TB2.TestGambler',
    haggler: 'TB2.TestHaggler',
    healer: 'TB2.TestHealer',
    hunter: 'TB2.TestHunter',
    jeweler: 'TB2.TestJeweler',
    laborer: 'TB2.TestLaborer',
    loremaster: 'TB2.TestLoremaster',
    manipulator: 'TB2.TestManipulator',
    mentor: 'TB2.TestMentor',
    orator: 'TB2.TestOrator',
    pathfinder: 'TB2.TestPathfinder',
    peasant: 'TB2.TestPeasant',
    persuader: 'TB2.TestPersuader',
    rider: 'TB2.TestRider',
    ritualist: 'TB2.TestRitualist',
    sailor: 'TB2.TestSailor',
    sapper: 'TB2.TestSapper',
    scavenger: 'TB2.TestScavenger',
    scholar: 'TB2.TestScholar',
    scout: 'TB2.TestScout',
    smith: 'TB2.TestSmith',
    steward: 'TB2.TestSteward',
    stonemason: 'TB2.TestStonemason',
    strategist: 'TB2.TestStrategist',
    survivalist: 'TB2.TestSurvivalist',
    tanner: 'TB2.TestTanner',
    theologian: 'TB2.TestTheologian',
    weaver: 'TB2.TestWeaver',
  },
  attributes: {
    health: 'TB.AttrHealth',
    will: 'TB.AttrWill',
    resources: 'TB.AttrResources',
    circles: 'TB.AttrCircles',
    nature: 'TB.AttrNature',
  },
  traits: {
    alert: 'TB2.TraitAlert',
    betweenTwoWorlds: 'TB2.TraitBetweenTwoWorlds',
    bodyguard: 'TB2.TraitBodyguard',
    cautious: 'TB2.TraitCautious',
    clever: 'TB2.TraitClever',
    compassionate: 'TB2.TraitCompassionate',
    conservative: 'TB2.TraitConservative',
    cynical: 'TB2.TraitCynical',
    defiant: 'TB2.TraitDefiant',
    desperate: 'TB2.TraitDesperate',
    determined: 'TB2.TraitDetermined',
    devilMayCare: 'TB2.TraitDevil May Care',
    driven: 'TB2.TraitDriven',
    emaciated: 'TB2.TraitEmaciated',
    fearful: 'TB2.TraitFearful',
    graceful: 'TB2.TraitGraceful',
    huldrekall: 'TB2.TraitHuldrekall',
    hungry: 'TB2.TraitHungry',
    independent: 'TB2.TraitIndependent',
    innocent: 'TB2.TraitInnocent',
    jovial: 'TB2.TraitJovial',
    juvenile: 'TB2.TraitJuvenile',
    keenEar: 'TB2.TraitKeen Ear',
    leader: 'TB2.TraitLeader',
    loyal: 'TB2.TraitLoyal',
    naturalBearings: 'TB2.TraitNatural Bearings',
    nightOwl: 'TB2.TraitNight Owl',
    nimble: 'TB2.TraitNimble',
    opportunistic: 'TB2.TraitOpportunistic',
    pragmatic: 'TB2.TraitPragmatic',
    restless: 'TB2.TraitRestless',
    rotund: 'TB2.TraitRotund',
    rover: 'TB2.TraitRover',
    short: 'TB2.TraitShort',
    skittish: 'TB2.TraitSkittish',
    stout: 'TB2.TraitStout',
    stubborn: 'TB2.TraitStubborn',
    suspicious: 'TB2.TraitSuspicious',
    tough: 'TB2.TraitTough',
    voiceOfThunder: 'TB2.TraitVoice of Thunder',
    weatherSense: 'TB2.TraitWeather Sense',
    wise: 'TB2.TraitWise',
    adventurous: 'TB2.TraitAdventurous',
    bitter: 'TB2.TraitBitter',
    bold: 'TB2.TraitBold',
    bornOfEarthAndStone: 'TB2.TraitBorn of Earth and Stone',
    brave: 'TB2.TraitBrave',
    calm: 'TB2.TraitCalm',
    cunning: 'TB2.TraitCunning',
    curious: 'TB2.TraitCurious',
    defender: 'TB2.TraitDefender',
    earlyRiser: 'TB2.TraitEarly Riser',
    extravagant: 'TB2.TraitExtravagant',
    extrovert: 'TB2.TraitExtrovert',
    fearless: 'TB2.TraitFearless',
    fiery: 'TB2.TraitFiery',
    firstBorn: 'TB2.TraitFirst Born',
    foolhardy: 'TB2.TraitFoolhardy',
    generous: 'TB2.TraitGenerous',
    heartofBattle: 'TB2.TraitHeart of Battle',
    hiddenDepths: 'TB2.TraitHidden Depths',
    honorable: 'TB2.TraitHonorable',
    jaded: 'TB2.TraitJaded',
    loner: 'TB2.TraitLoner',
    lost: 'TB2.TraitLost',
    quickWitted: 'TB2.TraitQuick-Witted',
    quiet: 'TB2.TraitQuiet',
    roughHands: 'TB2.TraitRough Hands',
    scarred: 'TB2.TraitScarred',
    sharpEyed: 'TB2.TraitSharp-Eyed',
    skeptical: 'TB2.TraitSkeptical',
    skinny: 'TB2.TraitSkinny',
    steadyHands: 'TB2.TraitSteady Hands',
    stoic: 'TB2.TraitStoic',
    tall: 'TB2.TraitTall',
    thoughtful: 'TB2.TraitThoughtful',
    touchedByTheGods: 'TB2.TraitTouched by the Gods',
    wizardsSight: 'TB2.TraitWizardsSight',
  },
};
export const TB = {
  i18n: i18nKeys,
  i18nKeys,
  icons: {},
};
